---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/gitea.com/sapk/explore

steps:
  - name: fetch-submodule
    pull: default
    image: docker:git
    commands:
      - git submodule update --init --recursive
  - name: frontend
    pull: always
    image: node
    commands:
      - cd assets/webapp
      - yarn install
      - yarn build
    when:
      event:
        - push
        - tag
        - pull_request

  - name: build
    pull: always
    image: golang:1.13
    environment:
      GOPROXY: https://goproxy.cn
    commands:
      - go run -mod=vendor mage.go generate
      - go run -mod=vendor mage.go build
    when:
      event:
        - push
        - tag
        - pull_request

---
kind: pipeline
name: docker-linux-amd64

platform:
  os: linux
  arch: amd64

workspace:
  base: /go
  path: src/gitea.com/sapk/explore

trigger:
  ref:
    - refs/heads/master
    - "refs/tags/**"
    - "refs/pull/**"

steps:
  - name: fetch-tags-submodule
    pull: default
    image: docker:git
    commands:
      - git fetch --tags --force
      - git submodule update --init --recursive
    when:
      event:
        exclude:
          - pull_request

  - name: dryrun
    pull: always
    image: plugins/docker:linux-amd64
    settings:
      dry_run: true
      repo: sapk/explore
      tags: linux-amd64
    when:
      event:
        - pull_request

  - name: publish
    pull: always
    image: plugins/docker:linux-amd64
    settings:
      dry_run: true
      repo: sapk/explore
      password:
        from_secret: docker_password
      username:
        from_secret: docker_username
    when:
      event:
        exclude:
          - pull_request
