// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// NewUserCurrentPostKeyParams creates a new UserCurrentPostKeyParams object
// with the default values initialized.
func NewUserCurrentPostKeyParams() *UserCurrentPostKeyParams {
	var ()
	return &UserCurrentPostKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUserCurrentPostKeyParamsWithTimeout creates a new UserCurrentPostKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUserCurrentPostKeyParamsWithTimeout(timeout time.Duration) *UserCurrentPostKeyParams {
	var ()
	return &UserCurrentPostKeyParams{

		timeout: timeout,
	}
}

// NewUserCurrentPostKeyParamsWithContext creates a new UserCurrentPostKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewUserCurrentPostKeyParamsWithContext(ctx context.Context) *UserCurrentPostKeyParams {
	var ()
	return &UserCurrentPostKeyParams{

		Context: ctx,
	}
}

// NewUserCurrentPostKeyParamsWithHTTPClient creates a new UserCurrentPostKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUserCurrentPostKeyParamsWithHTTPClient(client *http.Client) *UserCurrentPostKeyParams {
	var ()
	return &UserCurrentPostKeyParams{
		HTTPClient: client,
	}
}

/*UserCurrentPostKeyParams contains all the parameters to send to the API endpoint
for the user current post key operation typically these are written to a http.Request
*/
type UserCurrentPostKeyParams struct {

	/*Body*/
	Body *models.CreateKeyOption

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the user current post key params
func (o *UserCurrentPostKeyParams) WithTimeout(timeout time.Duration) *UserCurrentPostKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the user current post key params
func (o *UserCurrentPostKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the user current post key params
func (o *UserCurrentPostKeyParams) WithContext(ctx context.Context) *UserCurrentPostKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the user current post key params
func (o *UserCurrentPostKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the user current post key params
func (o *UserCurrentPostKeyParams) WithHTTPClient(client *http.Client) *UserCurrentPostKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the user current post key params
func (o *UserCurrentPostKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the user current post key params
func (o *UserCurrentPostKeyParams) WithBody(body *models.CreateKeyOption) *UserCurrentPostKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the user current post key params
func (o *UserCurrentPostKeyParams) SetBody(body *models.CreateKeyOption) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *UserCurrentPostKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
