// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// UserGetTokensReader is a Reader for the UserGetTokens structure.
type UserGetTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGetTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetTokensOK creates a UserGetTokensOK with default headers values
func NewUserGetTokensOK() *UserGetTokensOK {
	return &UserGetTokensOK{}
}

/*UserGetTokensOK handles this case with default header values.

AccessTokenList represents a list of API access token.
*/
type UserGetTokensOK struct {
	Payload []*models.AccessToken
}

func (o *UserGetTokensOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}/tokens][%d] userGetTokensOK  %+v", 200, o.Payload)
}

func (o *UserGetTokensOK) GetPayload() []*models.AccessToken {
	return o.Payload
}

func (o *UserGetTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
