// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// UserListEmailsReader is a Reader for the UserListEmails structure.
type UserListEmailsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserListEmailsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserListEmailsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserListEmailsOK creates a UserListEmailsOK with default headers values
func NewUserListEmailsOK() *UserListEmailsOK {
	return &UserListEmailsOK{}
}

/*UserListEmailsOK handles this case with default header values.

EmailList
*/
type UserListEmailsOK struct {
	Payload []*models.Email
}

func (o *UserListEmailsOK) Error() string {
	return fmt.Sprintf("[GET /user/emails][%d] userListEmailsOK  %+v", 200, o.Payload)
}

func (o *UserListEmailsOK) GetPayload() []*models.Email {
	return o.Payload
}

func (o *UserListEmailsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
