// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// UserDeleteAccessTokenReader is a Reader for the UserDeleteAccessToken structure.
type UserDeleteAccessTokenReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserDeleteAccessTokenReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewUserDeleteAccessTokenNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserDeleteAccessTokenNoContent creates a UserDeleteAccessTokenNoContent with default headers values
func NewUserDeleteAccessTokenNoContent() *UserDeleteAccessTokenNoContent {
	return &UserDeleteAccessTokenNoContent{}
}

/*UserDeleteAccessTokenNoContent handles this case with default header values.

APIEmpty is an empty response
*/
type UserDeleteAccessTokenNoContent struct {
}

func (o *UserDeleteAccessTokenNoContent) Error() string {
	return fmt.Sprintf("[DELETE /users/{username}/tokens/{token}][%d] userDeleteAccessTokenNoContent ", 204)
}

func (o *UserDeleteAccessTokenNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
