// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// UserTrackedTimesReader is a Reader for the UserTrackedTimes structure.
type UserTrackedTimesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserTrackedTimesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserTrackedTimesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserTrackedTimesOK creates a UserTrackedTimesOK with default headers values
func NewUserTrackedTimesOK() *UserTrackedTimesOK {
	return &UserTrackedTimesOK{}
}

/*UserTrackedTimesOK handles this case with default header values.

TrackedTimeList
*/
type UserTrackedTimesOK struct {
	Payload []*models.TrackedTime
}

func (o *UserTrackedTimesOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/times/{user}][%d] userTrackedTimesOK  %+v", 200, o.Payload)
}

func (o *UserTrackedTimesOK) GetPayload() []*models.TrackedTime {
	return o.Payload
}

func (o *UserTrackedTimesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
