// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// UserGetHeatmapDataReader is a Reader for the UserGetHeatmapData structure.
type UserGetHeatmapDataReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserGetHeatmapDataReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewUserGetHeatmapDataOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewUserGetHeatmapDataNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserGetHeatmapDataOK creates a UserGetHeatmapDataOK with default headers values
func NewUserGetHeatmapDataOK() *UserGetHeatmapDataOK {
	return &UserGetHeatmapDataOK{}
}

/*UserGetHeatmapDataOK handles this case with default header values.

UserHeatmapData
*/
type UserGetHeatmapDataOK struct {
	Payload []*models.UserHeatmapData
}

func (o *UserGetHeatmapDataOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}/heatmap][%d] userGetHeatmapDataOK  %+v", 200, o.Payload)
}

func (o *UserGetHeatmapDataOK) GetPayload() []*models.UserHeatmapData {
	return o.Payload
}

func (o *UserGetHeatmapDataOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUserGetHeatmapDataNotFound creates a UserGetHeatmapDataNotFound with default headers values
func NewUserGetHeatmapDataNotFound() *UserGetHeatmapDataNotFound {
	return &UserGetHeatmapDataNotFound{}
}

/*UserGetHeatmapDataNotFound handles this case with default header values.

APINotFound is a not found empty response
*/
type UserGetHeatmapDataNotFound struct {
}

func (o *UserGetHeatmapDataNotFound) Error() string {
	return fmt.Sprintf("[GET /users/{username}/heatmap][%d] userGetHeatmapDataNotFound ", 404)
}

func (o *UserGetHeatmapDataNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
