// Code generated by go-swagger; DO NOT EDIT.

package user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// UserAddEmailReader is a Reader for the UserAddEmail structure.
type UserAddEmailReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UserAddEmailReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUserAddEmailCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUserAddEmailCreated creates a UserAddEmailCreated with default headers values
func NewUserAddEmailCreated() *UserAddEmailCreated {
	return &UserAddEmailCreated{}
}

/*UserAddEmailCreated handles this case with default header values.

EmailList
*/
type UserAddEmailCreated struct {
	Payload []*models.Email
}

func (o *UserAddEmailCreated) Error() string {
	return fmt.Sprintf("[POST /user/emails][%d] userAddEmailCreated  %+v", 201, o.Payload)
}

func (o *UserAddEmailCreated) GetPayload() []*models.Email {
	return o.Payload
}

func (o *UserAddEmailCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
