// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgListCurrentUserOrgsReader is a Reader for the OrgListCurrentUserOrgs structure.
type OrgListCurrentUserOrgsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgListCurrentUserOrgsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgListCurrentUserOrgsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgListCurrentUserOrgsOK creates a OrgListCurrentUserOrgsOK with default headers values
func NewOrgListCurrentUserOrgsOK() *OrgListCurrentUserOrgsOK {
	return &OrgListCurrentUserOrgsOK{}
}

/*OrgListCurrentUserOrgsOK handles this case with default header values.

OrganizationList
*/
type OrgListCurrentUserOrgsOK struct {
	Payload []*models.Organization
}

func (o *OrgListCurrentUserOrgsOK) Error() string {
	return fmt.Sprintf("[GET /user/orgs][%d] orgListCurrentUserOrgsOK  %+v", 200, o.Payload)
}

func (o *OrgListCurrentUserOrgsOK) GetPayload() []*models.Organization {
	return o.Payload
}

func (o *OrgListCurrentUserOrgsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
