// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgRemoveTeamMemberReader is a Reader for the OrgRemoveTeamMember structure.
type OrgRemoveTeamMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgRemoveTeamMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOrgRemoveTeamMemberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgRemoveTeamMemberNoContent creates a OrgRemoveTeamMemberNoContent with default headers values
func NewOrgRemoveTeamMemberNoContent() *OrgRemoveTeamMemberNoContent {
	return &OrgRemoveTeamMemberNoContent{}
}

/*OrgRemoveTeamMemberNoContent handles this case with default header values.

APIEmpty is an empty response
*/
type OrgRemoveTeamMemberNoContent struct {
}

func (o *OrgRemoveTeamMemberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /teams/{id}/members/{username}][%d] orgRemoveTeamMemberNoContent ", 204)
}

func (o *OrgRemoveTeamMemberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
