// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// OrgIsMemberReader is a Reader for the OrgIsMember structure.
type OrgIsMemberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgIsMemberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewOrgIsMemberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewOrgIsMemberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgIsMemberNoContent creates a OrgIsMemberNoContent with default headers values
func NewOrgIsMemberNoContent() *OrgIsMemberNoContent {
	return &OrgIsMemberNoContent{}
}

/*OrgIsMemberNoContent handles this case with default header values.

user is a member
*/
type OrgIsMemberNoContent struct {
}

func (o *OrgIsMemberNoContent) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/members/{username}][%d] orgIsMemberNoContent ", 204)
}

func (o *OrgIsMemberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewOrgIsMemberNotFound creates a OrgIsMemberNotFound with default headers values
func NewOrgIsMemberNotFound() *OrgIsMemberNotFound {
	return &OrgIsMemberNotFound{}
}

/*OrgIsMemberNotFound handles this case with default header values.

user is not a member
*/
type OrgIsMemberNotFound struct {
}

func (o *OrgIsMemberNotFound) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/members/{username}][%d] orgIsMemberNotFound ", 404)
}

func (o *OrgIsMemberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
