// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgListUserOrgsReader is a Reader for the OrgListUserOrgs structure.
type OrgListUserOrgsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgListUserOrgsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgListUserOrgsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgListUserOrgsOK creates a OrgListUserOrgsOK with default headers values
func NewOrgListUserOrgsOK() *OrgListUserOrgsOK {
	return &OrgListUserOrgsOK{}
}

/*OrgListUserOrgsOK handles this case with default header values.

OrganizationList
*/
type OrgListUserOrgsOK struct {
	Payload []*models.Organization
}

func (o *OrgListUserOrgsOK) Error() string {
	return fmt.Sprintf("[GET /users/{username}/orgs][%d] orgListUserOrgsOK  %+v", 200, o.Payload)
}

func (o *OrgListUserOrgsOK) GetPayload() []*models.Organization {
	return o.Payload
}

func (o *OrgListUserOrgsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
