// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgListPublicMembersReader is a Reader for the OrgListPublicMembers structure.
type OrgListPublicMembersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgListPublicMembersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgListPublicMembersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgListPublicMembersOK creates a OrgListPublicMembersOK with default headers values
func NewOrgListPublicMembersOK() *OrgListPublicMembersOK {
	return &OrgListPublicMembersOK{}
}

/*OrgListPublicMembersOK handles this case with default header values.

UserList
*/
type OrgListPublicMembersOK struct {
	Payload []*models.User
}

func (o *OrgListPublicMembersOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/public_members][%d] orgListPublicMembersOK  %+v", 200, o.Payload)
}

func (o *OrgListPublicMembersOK) GetPayload() []*models.User {
	return o.Payload
}

func (o *OrgListPublicMembersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
