// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgRemoveTeamRepositoryParams creates a new OrgRemoveTeamRepositoryParams object
// with the default values initialized.
func NewOrgRemoveTeamRepositoryParams() *OrgRemoveTeamRepositoryParams {
	var ()
	return &OrgRemoveTeamRepositoryParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgRemoveTeamRepositoryParamsWithTimeout creates a new OrgRemoveTeamRepositoryParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgRemoveTeamRepositoryParamsWithTimeout(timeout time.Duration) *OrgRemoveTeamRepositoryParams {
	var ()
	return &OrgRemoveTeamRepositoryParams{

		timeout: timeout,
	}
}

// NewOrgRemoveTeamRepositoryParamsWithContext creates a new OrgRemoveTeamRepositoryParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgRemoveTeamRepositoryParamsWithContext(ctx context.Context) *OrgRemoveTeamRepositoryParams {
	var ()
	return &OrgRemoveTeamRepositoryParams{

		Context: ctx,
	}
}

// NewOrgRemoveTeamRepositoryParamsWithHTTPClient creates a new OrgRemoveTeamRepositoryParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgRemoveTeamRepositoryParamsWithHTTPClient(client *http.Client) *OrgRemoveTeamRepositoryParams {
	var ()
	return &OrgRemoveTeamRepositoryParams{
		HTTPClient: client,
	}
}

/*OrgRemoveTeamRepositoryParams contains all the parameters to send to the API endpoint
for the org remove team repository operation typically these are written to a http.Request
*/
type OrgRemoveTeamRepositoryParams struct {

	/*ID
	  id of the team

	*/
	ID int64
	/*Org
	  organization that owns the repo to remove

	*/
	Org string
	/*Repo
	  name of the repo to remove

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithTimeout(timeout time.Duration) *OrgRemoveTeamRepositoryParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithContext(ctx context.Context) *OrgRemoveTeamRepositoryParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithHTTPClient(client *http.Client) *OrgRemoveTeamRepositoryParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithID(id int64) *OrgRemoveTeamRepositoryParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetID(id int64) {
	o.ID = id
}

// WithOrg adds the org to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithOrg(org string) *OrgRemoveTeamRepositoryParams {
	o.SetOrg(org)
	return o
}

// SetOrg adds the org to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetOrg(org string) {
	o.Org = org
}

// WithRepo adds the repo to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) WithRepo(repo string) *OrgRemoveTeamRepositoryParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the org remove team repository params
func (o *OrgRemoveTeamRepositoryParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *OrgRemoveTeamRepositoryParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param org
	if err := r.SetPathParam("org", o.Org); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
