// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgCreateTeamReader is a Reader for the OrgCreateTeam structure.
type OrgCreateTeamReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgCreateTeamReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrgCreateTeamCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgCreateTeamCreated creates a OrgCreateTeamCreated with default headers values
func NewOrgCreateTeamCreated() *OrgCreateTeamCreated {
	return &OrgCreateTeamCreated{}
}

/*OrgCreateTeamCreated handles this case with default header values.

Team
*/
type OrgCreateTeamCreated struct {
	Payload *models.Team
}

func (o *OrgCreateTeamCreated) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/teams][%d] orgCreateTeamCreated  %+v", 201, o.Payload)
}

func (o *OrgCreateTeamCreated) GetPayload() *models.Team {
	return o.Payload
}

func (o *OrgCreateTeamCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Team)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
