// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgGetReader is a Reader for the OrgGet structure.
type OrgGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgGetOK creates a OrgGetOK with default headers values
func NewOrgGetOK() *OrgGetOK {
	return &OrgGetOK{}
}

/*OrgGetOK handles this case with default header values.

Organization
*/
type OrgGetOK struct {
	Payload *models.Organization
}

func (o *OrgGetOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}][%d] orgGetOK  %+v", 200, o.Payload)
}

func (o *OrgGetOK) GetPayload() *models.Organization {
	return o.Payload
}

func (o *OrgGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Organization)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
