// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgListHooksReader is a Reader for the OrgListHooks structure.
type OrgListHooksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgListHooksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOrgListHooksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgListHooksOK creates a OrgListHooksOK with default headers values
func NewOrgListHooksOK() *OrgListHooksOK {
	return &OrgListHooksOK{}
}

/*OrgListHooksOK handles this case with default header values.

HookList
*/
type OrgListHooksOK struct {
	Payload []*models.Hook
}

func (o *OrgListHooksOK) Error() string {
	return fmt.Sprintf("[GET /orgs/{org}/hooks][%d] orgListHooksOK  %+v", 200, o.Payload)
}

func (o *OrgListHooksOK) GetPayload() []*models.Hook {
	return o.Payload
}

func (o *OrgListHooksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
