// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewOrgListCurrentUserOrgsParams creates a new OrgListCurrentUserOrgsParams object
// with the default values initialized.
func NewOrgListCurrentUserOrgsParams() *OrgListCurrentUserOrgsParams {

	return &OrgListCurrentUserOrgsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewOrgListCurrentUserOrgsParamsWithTimeout creates a new OrgListCurrentUserOrgsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewOrgListCurrentUserOrgsParamsWithTimeout(timeout time.Duration) *OrgListCurrentUserOrgsParams {

	return &OrgListCurrentUserOrgsParams{

		timeout: timeout,
	}
}

// NewOrgListCurrentUserOrgsParamsWithContext creates a new OrgListCurrentUserOrgsParams object
// with the default values initialized, and the ability to set a context for a request
func NewOrgListCurrentUserOrgsParamsWithContext(ctx context.Context) *OrgListCurrentUserOrgsParams {

	return &OrgListCurrentUserOrgsParams{

		Context: ctx,
	}
}

// NewOrgListCurrentUserOrgsParamsWithHTTPClient creates a new OrgListCurrentUserOrgsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewOrgListCurrentUserOrgsParamsWithHTTPClient(client *http.Client) *OrgListCurrentUserOrgsParams {

	return &OrgListCurrentUserOrgsParams{
		HTTPClient: client,
	}
}

/*OrgListCurrentUserOrgsParams contains all the parameters to send to the API endpoint
for the org list current user orgs operation typically these are written to a http.Request
*/
type OrgListCurrentUserOrgsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) WithTimeout(timeout time.Duration) *OrgListCurrentUserOrgsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) WithContext(ctx context.Context) *OrgListCurrentUserOrgsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) WithHTTPClient(client *http.Client) *OrgListCurrentUserOrgsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the org list current user orgs params
func (o *OrgListCurrentUserOrgsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OrgListCurrentUserOrgsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
