// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// OrgCreateHookReader is a Reader for the OrgCreateHook structure.
type OrgCreateHookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OrgCreateHookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewOrgCreateHookCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewOrgCreateHookCreated creates a OrgCreateHookCreated with default headers values
func NewOrgCreateHookCreated() *OrgCreateHookCreated {
	return &OrgCreateHookCreated{}
}

/*OrgCreateHookCreated handles this case with default header values.

Hook
*/
type OrgCreateHookCreated struct {
	Payload *models.Hook
}

func (o *OrgCreateHookCreated) Error() string {
	return fmt.Sprintf("[POST /orgs/{org}/hooks/][%d] orgCreateHookCreated  %+v", 201, o.Payload)
}

func (o *OrgCreateHookCreated) GetPayload() *models.Hook {
	return o.Payload
}

func (o *OrgCreateHookCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Hook)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
