// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAdminDeleteUserPublicKeyParams creates a new AdminDeleteUserPublicKeyParams object
// with the default values initialized.
func NewAdminDeleteUserPublicKeyParams() *AdminDeleteUserPublicKeyParams {
	var ()
	return &AdminDeleteUserPublicKeyParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAdminDeleteUserPublicKeyParamsWithTimeout creates a new AdminDeleteUserPublicKeyParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAdminDeleteUserPublicKeyParamsWithTimeout(timeout time.Duration) *AdminDeleteUserPublicKeyParams {
	var ()
	return &AdminDeleteUserPublicKeyParams{

		timeout: timeout,
	}
}

// NewAdminDeleteUserPublicKeyParamsWithContext creates a new AdminDeleteUserPublicKeyParams object
// with the default values initialized, and the ability to set a context for a request
func NewAdminDeleteUserPublicKeyParamsWithContext(ctx context.Context) *AdminDeleteUserPublicKeyParams {
	var ()
	return &AdminDeleteUserPublicKeyParams{

		Context: ctx,
	}
}

// NewAdminDeleteUserPublicKeyParamsWithHTTPClient creates a new AdminDeleteUserPublicKeyParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAdminDeleteUserPublicKeyParamsWithHTTPClient(client *http.Client) *AdminDeleteUserPublicKeyParams {
	var ()
	return &AdminDeleteUserPublicKeyParams{
		HTTPClient: client,
	}
}

/*AdminDeleteUserPublicKeyParams contains all the parameters to send to the API endpoint
for the admin delete user public key operation typically these are written to a http.Request
*/
type AdminDeleteUserPublicKeyParams struct {

	/*ID
	  id of the key to delete

	*/
	ID int64
	/*Username
	  username of user

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) WithTimeout(timeout time.Duration) *AdminDeleteUserPublicKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) WithContext(ctx context.Context) *AdminDeleteUserPublicKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) WithHTTPClient(client *http.Client) *AdminDeleteUserPublicKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) WithID(id int64) *AdminDeleteUserPublicKeyParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) SetID(id int64) {
	o.ID = id
}

// WithUsername adds the username to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) WithUsername(username string) *AdminDeleteUserPublicKeyParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the admin delete user public key params
func (o *AdminDeleteUserPublicKeyParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *AdminDeleteUserPublicKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param username
	if err := r.SetPathParam("username", o.Username); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
