// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAdminGetAllUsersParams creates a new AdminGetAllUsersParams object
// with the default values initialized.
func NewAdminGetAllUsersParams() *AdminGetAllUsersParams {

	return &AdminGetAllUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewAdminGetAllUsersParamsWithTimeout creates a new AdminGetAllUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewAdminGetAllUsersParamsWithTimeout(timeout time.Duration) *AdminGetAllUsersParams {

	return &AdminGetAllUsersParams{

		timeout: timeout,
	}
}

// NewAdminGetAllUsersParamsWithContext creates a new AdminGetAllUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewAdminGetAllUsersParamsWithContext(ctx context.Context) *AdminGetAllUsersParams {

	return &AdminGetAllUsersParams{

		Context: ctx,
	}
}

// NewAdminGetAllUsersParamsWithHTTPClient creates a new AdminGetAllUsersParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewAdminGetAllUsersParamsWithHTTPClient(client *http.Client) *AdminGetAllUsersParams {

	return &AdminGetAllUsersParams{
		HTTPClient: client,
	}
}

/*AdminGetAllUsersParams contains all the parameters to send to the API endpoint
for the admin get all users operation typically these are written to a http.Request
*/
type AdminGetAllUsersParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the admin get all users params
func (o *AdminGetAllUsersParams) WithTimeout(timeout time.Duration) *AdminGetAllUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the admin get all users params
func (o *AdminGetAllUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the admin get all users params
func (o *AdminGetAllUsersParams) WithContext(ctx context.Context) *AdminGetAllUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the admin get all users params
func (o *AdminGetAllUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the admin get all users params
func (o *AdminGetAllUsersParams) WithHTTPClient(client *http.Client) *AdminGetAllUsersParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the admin get all users params
func (o *AdminGetAllUsersParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AdminGetAllUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
