// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// IssueDeleteLabelReader is a Reader for the IssueDeleteLabel structure.
type IssueDeleteLabelReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueDeleteLabelReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewIssueDeleteLabelNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIssueDeleteLabelNoContent creates a IssueDeleteLabelNoContent with default headers values
func NewIssueDeleteLabelNoContent() *IssueDeleteLabelNoContent {
	return &IssueDeleteLabelNoContent{}
}

/*IssueDeleteLabelNoContent handles this case with default header values.

APIEmpty is an empty response
*/
type IssueDeleteLabelNoContent struct {
}

func (o *IssueDeleteLabelNoContent) Error() string {
	return fmt.Sprintf("[DELETE /repos/{owner}/{repo}/labels/{id}][%d] issueDeleteLabelNoContent ", 204)
}

func (o *IssueDeleteLabelNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
