// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// IssueGetCommentsReader is a Reader for the IssueGetComments structure.
type IssueGetCommentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueGetCommentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIssueGetCommentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIssueGetCommentsOK creates a IssueGetCommentsOK with default headers values
func NewIssueGetCommentsOK() *IssueGetCommentsOK {
	return &IssueGetCommentsOK{}
}

/*IssueGetCommentsOK handles this case with default header values.

CommentList
*/
type IssueGetCommentsOK struct {
	Payload []*models.Comment
}

func (o *IssueGetCommentsOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/issues/{index}/comments][%d] issueGetCommentsOK  %+v", 200, o.Payload)
}

func (o *IssueGetCommentsOK) GetPayload() []*models.Comment {
	return o.Payload
}

func (o *IssueGetCommentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
