// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIssueDeleteLabelParams creates a new IssueDeleteLabelParams object
// with the default values initialized.
func NewIssueDeleteLabelParams() *IssueDeleteLabelParams {
	var ()
	return &IssueDeleteLabelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIssueDeleteLabelParamsWithTimeout creates a new IssueDeleteLabelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIssueDeleteLabelParamsWithTimeout(timeout time.Duration) *IssueDeleteLabelParams {
	var ()
	return &IssueDeleteLabelParams{

		timeout: timeout,
	}
}

// NewIssueDeleteLabelParamsWithContext creates a new IssueDeleteLabelParams object
// with the default values initialized, and the ability to set a context for a request
func NewIssueDeleteLabelParamsWithContext(ctx context.Context) *IssueDeleteLabelParams {
	var ()
	return &IssueDeleteLabelParams{

		Context: ctx,
	}
}

// NewIssueDeleteLabelParamsWithHTTPClient creates a new IssueDeleteLabelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIssueDeleteLabelParamsWithHTTPClient(client *http.Client) *IssueDeleteLabelParams {
	var ()
	return &IssueDeleteLabelParams{
		HTTPClient: client,
	}
}

/*IssueDeleteLabelParams contains all the parameters to send to the API endpoint
for the issue delete label operation typically these are written to a http.Request
*/
type IssueDeleteLabelParams struct {

	/*ID
	  id of the label to delete

	*/
	ID int64
	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the issue delete label params
func (o *IssueDeleteLabelParams) WithTimeout(timeout time.Duration) *IssueDeleteLabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue delete label params
func (o *IssueDeleteLabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue delete label params
func (o *IssueDeleteLabelParams) WithContext(ctx context.Context) *IssueDeleteLabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue delete label params
func (o *IssueDeleteLabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue delete label params
func (o *IssueDeleteLabelParams) WithHTTPClient(client *http.Client) *IssueDeleteLabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue delete label params
func (o *IssueDeleteLabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the issue delete label params
func (o *IssueDeleteLabelParams) WithID(id int64) *IssueDeleteLabelParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the issue delete label params
func (o *IssueDeleteLabelParams) SetID(id int64) {
	o.ID = id
}

// WithOwner adds the owner to the issue delete label params
func (o *IssueDeleteLabelParams) WithOwner(owner string) *IssueDeleteLabelParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the issue delete label params
func (o *IssueDeleteLabelParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the issue delete label params
func (o *IssueDeleteLabelParams) WithRepo(repo string) *IssueDeleteLabelParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the issue delete label params
func (o *IssueDeleteLabelParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *IssueDeleteLabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
