// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewIssueDeleteMilestoneParams creates a new IssueDeleteMilestoneParams object
// with the default values initialized.
func NewIssueDeleteMilestoneParams() *IssueDeleteMilestoneParams {
	var ()
	return &IssueDeleteMilestoneParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIssueDeleteMilestoneParamsWithTimeout creates a new IssueDeleteMilestoneParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIssueDeleteMilestoneParamsWithTimeout(timeout time.Duration) *IssueDeleteMilestoneParams {
	var ()
	return &IssueDeleteMilestoneParams{

		timeout: timeout,
	}
}

// NewIssueDeleteMilestoneParamsWithContext creates a new IssueDeleteMilestoneParams object
// with the default values initialized, and the ability to set a context for a request
func NewIssueDeleteMilestoneParamsWithContext(ctx context.Context) *IssueDeleteMilestoneParams {
	var ()
	return &IssueDeleteMilestoneParams{

		Context: ctx,
	}
}

// NewIssueDeleteMilestoneParamsWithHTTPClient creates a new IssueDeleteMilestoneParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIssueDeleteMilestoneParamsWithHTTPClient(client *http.Client) *IssueDeleteMilestoneParams {
	var ()
	return &IssueDeleteMilestoneParams{
		HTTPClient: client,
	}
}

/*IssueDeleteMilestoneParams contains all the parameters to send to the API endpoint
for the issue delete milestone operation typically these are written to a http.Request
*/
type IssueDeleteMilestoneParams struct {

	/*ID
	  id of the milestone to delete

	*/
	ID int64
	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithTimeout(timeout time.Duration) *IssueDeleteMilestoneParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithContext(ctx context.Context) *IssueDeleteMilestoneParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithHTTPClient(client *http.Client) *IssueDeleteMilestoneParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithID(id int64) *IssueDeleteMilestoneParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetID(id int64) {
	o.ID = id
}

// WithOwner adds the owner to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithOwner(owner string) *IssueDeleteMilestoneParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) WithRepo(repo string) *IssueDeleteMilestoneParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the issue delete milestone params
func (o *IssueDeleteMilestoneParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *IssueDeleteMilestoneParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
