// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// IssueGetMilestoneReader is a Reader for the IssueGetMilestone structure.
type IssueGetMilestoneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IssueGetMilestoneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewIssueGetMilestoneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewIssueGetMilestoneOK creates a IssueGetMilestoneOK with default headers values
func NewIssueGetMilestoneOK() *IssueGetMilestoneOK {
	return &IssueGetMilestoneOK{}
}

/*IssueGetMilestoneOK handles this case with default header values.

Milestone
*/
type IssueGetMilestoneOK struct {
	Payload *models.Milestone
}

func (o *IssueGetMilestoneOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/milestones/{id}][%d] issueGetMilestoneOK  %+v", 200, o.Payload)
}

func (o *IssueGetMilestoneOK) GetPayload() *models.Milestone {
	return o.Payload
}

func (o *IssueGetMilestoneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Milestone)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
