// Code generated by go-swagger; DO NOT EDIT.

package issue

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// NewIssueAddLabelParams creates a new IssueAddLabelParams object
// with the default values initialized.
func NewIssueAddLabelParams() *IssueAddLabelParams {
	var ()
	return &IssueAddLabelParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewIssueAddLabelParamsWithTimeout creates a new IssueAddLabelParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewIssueAddLabelParamsWithTimeout(timeout time.Duration) *IssueAddLabelParams {
	var ()
	return &IssueAddLabelParams{

		timeout: timeout,
	}
}

// NewIssueAddLabelParamsWithContext creates a new IssueAddLabelParams object
// with the default values initialized, and the ability to set a context for a request
func NewIssueAddLabelParamsWithContext(ctx context.Context) *IssueAddLabelParams {
	var ()
	return &IssueAddLabelParams{

		Context: ctx,
	}
}

// NewIssueAddLabelParamsWithHTTPClient creates a new IssueAddLabelParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewIssueAddLabelParamsWithHTTPClient(client *http.Client) *IssueAddLabelParams {
	var ()
	return &IssueAddLabelParams{
		HTTPClient: client,
	}
}

/*IssueAddLabelParams contains all the parameters to send to the API endpoint
for the issue add label operation typically these are written to a http.Request
*/
type IssueAddLabelParams struct {

	/*Body*/
	Body *models.IssueLabelsOption
	/*Index
	  index of the issue

	*/
	Index int64
	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the issue add label params
func (o *IssueAddLabelParams) WithTimeout(timeout time.Duration) *IssueAddLabelParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the issue add label params
func (o *IssueAddLabelParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the issue add label params
func (o *IssueAddLabelParams) WithContext(ctx context.Context) *IssueAddLabelParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the issue add label params
func (o *IssueAddLabelParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the issue add label params
func (o *IssueAddLabelParams) WithHTTPClient(client *http.Client) *IssueAddLabelParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the issue add label params
func (o *IssueAddLabelParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the issue add label params
func (o *IssueAddLabelParams) WithBody(body *models.IssueLabelsOption) *IssueAddLabelParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the issue add label params
func (o *IssueAddLabelParams) SetBody(body *models.IssueLabelsOption) {
	o.Body = body
}

// WithIndex adds the index to the issue add label params
func (o *IssueAddLabelParams) WithIndex(index int64) *IssueAddLabelParams {
	o.SetIndex(index)
	return o
}

// SetIndex adds the index to the issue add label params
func (o *IssueAddLabelParams) SetIndex(index int64) {
	o.Index = index
}

// WithOwner adds the owner to the issue add label params
func (o *IssueAddLabelParams) WithOwner(owner string) *IssueAddLabelParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the issue add label params
func (o *IssueAddLabelParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the issue add label params
func (o *IssueAddLabelParams) WithRepo(repo string) *IssueAddLabelParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the issue add label params
func (o *IssueAddLabelParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *IssueAddLabelParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param index
	if err := r.SetPathParam("index", swag.FormatInt64(o.Index)); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
