// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// CreateForkReader is a Reader for the CreateFork structure.
type CreateForkReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateForkReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewCreateForkAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateForkAccepted creates a CreateForkAccepted with default headers values
func NewCreateForkAccepted() *CreateForkAccepted {
	return &CreateForkAccepted{}
}

/*CreateForkAccepted handles this case with default header values.

Repository
*/
type CreateForkAccepted struct {
	Payload *models.Repository
}

func (o *CreateForkAccepted) Error() string {
	return fmt.Sprintf("[POST /repos/{owner}/{repo}/forks][%d] createForkAccepted  %+v", 202, o.Payload)
}

func (o *CreateForkAccepted) GetPayload() *models.Repository {
	return o.Payload
}

func (o *CreateForkAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Repository)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
