// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetTagParams creates a new GetTagParams object
// with the default values initialized.
func NewGetTagParams() *GetTagParams {
	var ()
	return &GetTagParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetTagParamsWithTimeout creates a new GetTagParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetTagParamsWithTimeout(timeout time.Duration) *GetTagParams {
	var ()
	return &GetTagParams{

		timeout: timeout,
	}
}

// NewGetTagParamsWithContext creates a new GetTagParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetTagParamsWithContext(ctx context.Context) *GetTagParams {
	var ()
	return &GetTagParams{

		Context: ctx,
	}
}

// NewGetTagParamsWithHTTPClient creates a new GetTagParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetTagParamsWithHTTPClient(client *http.Client) *GetTagParams {
	var ()
	return &GetTagParams{
		HTTPClient: client,
	}
}

/*GetTagParams contains all the parameters to send to the API endpoint
for the get tag operation typically these are written to a http.Request
*/
type GetTagParams struct {

	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string
	/*Sha
	  sha of the tag. The Git tags API only supports annotated tag objects, not lightweight tags.

	*/
	Sha string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get tag params
func (o *GetTagParams) WithTimeout(timeout time.Duration) *GetTagParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get tag params
func (o *GetTagParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get tag params
func (o *GetTagParams) WithContext(ctx context.Context) *GetTagParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get tag params
func (o *GetTagParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get tag params
func (o *GetTagParams) WithHTTPClient(client *http.Client) *GetTagParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get tag params
func (o *GetTagParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the get tag params
func (o *GetTagParams) WithOwner(owner string) *GetTagParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the get tag params
func (o *GetTagParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the get tag params
func (o *GetTagParams) WithRepo(repo string) *GetTagParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the get tag params
func (o *GetTagParams) SetRepo(repo string) {
	o.Repo = repo
}

// WithSha adds the sha to the get tag params
func (o *GetTagParams) WithSha(sha string) *GetTagParams {
	o.SetSha(sha)
	return o
}

// SetSha adds the sha to the get tag params
func (o *GetTagParams) SetSha(sha string) {
	o.Sha = sha
}

// WriteToRequest writes these params to a swagger request
func (o *GetTagParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	// path param sha
	if err := r.SetPathParam("sha", o.Sha); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
