// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// GetTreeReader is a Reader for the GetTree structure.
type GetTreeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTreeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTreeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetTreeOK creates a GetTreeOK with default headers values
func NewGetTreeOK() *GetTreeOK {
	return &GetTreeOK{}
}

/*GetTreeOK handles this case with default header values.

GitTreeResponse
*/
type GetTreeOK struct {
	Payload *models.GitTreeResponse
}

func (o *GetTreeOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/git/trees/{sha}][%d] getTreeOK  %+v", 200, o.Payload)
}

func (o *GetTreeOK) GetPayload() *models.GitTreeResponse {
	return o.Payload
}

func (o *GetTreeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GitTreeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
