// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// ListForksReader is a Reader for the ListForks structure.
type ListForksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListForksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListForksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListForksOK creates a ListForksOK with default headers values
func NewListForksOK() *ListForksOK {
	return &ListForksOK{}
}

/*ListForksOK handles this case with default header values.

RepositoryList
*/
type ListForksOK struct {
	Payload []*models.Repository
}

func (o *ListForksOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/forks][%d] listForksOK  %+v", 200, o.Payload)
}

func (o *ListForksOK) GetPayload() []*models.Repository {
	return o.Payload
}

func (o *ListForksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
