// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// NewRepoEditReleaseParams creates a new RepoEditReleaseParams object
// with the default values initialized.
func NewRepoEditReleaseParams() *RepoEditReleaseParams {
	var ()
	return &RepoEditReleaseParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRepoEditReleaseParamsWithTimeout creates a new RepoEditReleaseParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRepoEditReleaseParamsWithTimeout(timeout time.Duration) *RepoEditReleaseParams {
	var ()
	return &RepoEditReleaseParams{

		timeout: timeout,
	}
}

// NewRepoEditReleaseParamsWithContext creates a new RepoEditReleaseParams object
// with the default values initialized, and the ability to set a context for a request
func NewRepoEditReleaseParamsWithContext(ctx context.Context) *RepoEditReleaseParams {
	var ()
	return &RepoEditReleaseParams{

		Context: ctx,
	}
}

// NewRepoEditReleaseParamsWithHTTPClient creates a new RepoEditReleaseParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRepoEditReleaseParamsWithHTTPClient(client *http.Client) *RepoEditReleaseParams {
	var ()
	return &RepoEditReleaseParams{
		HTTPClient: client,
	}
}

/*RepoEditReleaseParams contains all the parameters to send to the API endpoint
for the repo edit release operation typically these are written to a http.Request
*/
type RepoEditReleaseParams struct {

	/*Body*/
	Body *models.EditReleaseOption
	/*ID
	  id of the release to edit

	*/
	ID int64
	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repo edit release params
func (o *RepoEditReleaseParams) WithTimeout(timeout time.Duration) *RepoEditReleaseParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repo edit release params
func (o *RepoEditReleaseParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repo edit release params
func (o *RepoEditReleaseParams) WithContext(ctx context.Context) *RepoEditReleaseParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repo edit release params
func (o *RepoEditReleaseParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repo edit release params
func (o *RepoEditReleaseParams) WithHTTPClient(client *http.Client) *RepoEditReleaseParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repo edit release params
func (o *RepoEditReleaseParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the repo edit release params
func (o *RepoEditReleaseParams) WithBody(body *models.EditReleaseOption) *RepoEditReleaseParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the repo edit release params
func (o *RepoEditReleaseParams) SetBody(body *models.EditReleaseOption) {
	o.Body = body
}

// WithID adds the id to the repo edit release params
func (o *RepoEditReleaseParams) WithID(id int64) *RepoEditReleaseParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the repo edit release params
func (o *RepoEditReleaseParams) SetID(id int64) {
	o.ID = id
}

// WithOwner adds the owner to the repo edit release params
func (o *RepoEditReleaseParams) WithOwner(owner string) *RepoEditReleaseParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the repo edit release params
func (o *RepoEditReleaseParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the repo edit release params
func (o *RepoEditReleaseParams) WithRepo(repo string) *RepoEditReleaseParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the repo edit release params
func (o *RepoEditReleaseParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *RepoEditReleaseParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", swag.FormatInt64(o.ID)); err != nil {
		return err
	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
