// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RepoDeleteCollaboratorReader is a Reader for the RepoDeleteCollaborator structure.
type RepoDeleteCollaboratorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoDeleteCollaboratorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRepoDeleteCollaboratorNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoDeleteCollaboratorNoContent creates a RepoDeleteCollaboratorNoContent with default headers values
func NewRepoDeleteCollaboratorNoContent() *RepoDeleteCollaboratorNoContent {
	return &RepoDeleteCollaboratorNoContent{}
}

/*RepoDeleteCollaboratorNoContent handles this case with default header values.

APIEmpty is an empty response
*/
type RepoDeleteCollaboratorNoContent struct {
}

func (o *RepoDeleteCollaboratorNoContent) Error() string {
	return fmt.Sprintf("[DELETE /repos/{owner}/{repo}/collaborators/{collaborator}][%d] repoDeleteCollaboratorNoContent ", 204)
}

func (o *RepoDeleteCollaboratorNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
