// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// RepoGetReleaseReader is a Reader for the RepoGetRelease structure.
type RepoGetReleaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoGetReleaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoGetReleaseOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoGetReleaseOK creates a RepoGetReleaseOK with default headers values
func NewRepoGetReleaseOK() *RepoGetReleaseOK {
	return &RepoGetReleaseOK{}
}

/*RepoGetReleaseOK handles this case with default header values.

Release
*/
type RepoGetReleaseOK struct {
	Payload *models.Release
}

func (o *RepoGetReleaseOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/releases/{id}][%d] repoGetReleaseOK  %+v", 200, o.Payload)
}

func (o *RepoGetReleaseOK) GetPayload() *models.Release {
	return o.Payload
}

func (o *RepoGetReleaseOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Release)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
