// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RepoCheckCollaboratorReader is a Reader for the RepoCheckCollaborator structure.
type RepoCheckCollaboratorReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCheckCollaboratorReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewRepoCheckCollaboratorNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewRepoCheckCollaboratorNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoCheckCollaboratorNoContent creates a RepoCheckCollaboratorNoContent with default headers values
func NewRepoCheckCollaboratorNoContent() *RepoCheckCollaboratorNoContent {
	return &RepoCheckCollaboratorNoContent{}
}

/*RepoCheckCollaboratorNoContent handles this case with default header values.

APIEmpty is an empty response
*/
type RepoCheckCollaboratorNoContent struct {
}

func (o *RepoCheckCollaboratorNoContent) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/collaborators/{collaborator}][%d] repoCheckCollaboratorNoContent ", 204)
}

func (o *RepoCheckCollaboratorNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewRepoCheckCollaboratorNotFound creates a RepoCheckCollaboratorNotFound with default headers values
func NewRepoCheckCollaboratorNotFound() *RepoCheckCollaboratorNotFound {
	return &RepoCheckCollaboratorNotFound{}
}

/*RepoCheckCollaboratorNotFound handles this case with default header values.

APIEmpty is an empty response
*/
type RepoCheckCollaboratorNotFound struct {
}

func (o *RepoCheckCollaboratorNotFound) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/collaborators/{collaborator}][%d] repoCheckCollaboratorNotFound ", 404)
}

func (o *RepoCheckCollaboratorNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
