// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// RepoGetArchiveReader is a Reader for the RepoGetArchive structure.
type RepoGetArchiveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoGetArchiveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoGetArchiveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoGetArchiveOK creates a RepoGetArchiveOK with default headers values
func NewRepoGetArchiveOK() *RepoGetArchiveOK {
	return &RepoGetArchiveOK{}
}

/*RepoGetArchiveOK handles this case with default header values.

success
*/
type RepoGetArchiveOK struct {
}

func (o *RepoGetArchiveOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/archive/{archive}][%d] repoGetArchiveOK ", 200)
}

func (o *RepoGetArchiveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
