// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRepoListHooksParams creates a new RepoListHooksParams object
// with the default values initialized.
func NewRepoListHooksParams() *RepoListHooksParams {
	var ()
	return &RepoListHooksParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRepoListHooksParamsWithTimeout creates a new RepoListHooksParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRepoListHooksParamsWithTimeout(timeout time.Duration) *RepoListHooksParams {
	var ()
	return &RepoListHooksParams{

		timeout: timeout,
	}
}

// NewRepoListHooksParamsWithContext creates a new RepoListHooksParams object
// with the default values initialized, and the ability to set a context for a request
func NewRepoListHooksParamsWithContext(ctx context.Context) *RepoListHooksParams {
	var ()
	return &RepoListHooksParams{

		Context: ctx,
	}
}

// NewRepoListHooksParamsWithHTTPClient creates a new RepoListHooksParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRepoListHooksParamsWithHTTPClient(client *http.Client) *RepoListHooksParams {
	var ()
	return &RepoListHooksParams{
		HTTPClient: client,
	}
}

/*RepoListHooksParams contains all the parameters to send to the API endpoint
for the repo list hooks operation typically these are written to a http.Request
*/
type RepoListHooksParams struct {

	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repo list hooks params
func (o *RepoListHooksParams) WithTimeout(timeout time.Duration) *RepoListHooksParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repo list hooks params
func (o *RepoListHooksParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repo list hooks params
func (o *RepoListHooksParams) WithContext(ctx context.Context) *RepoListHooksParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repo list hooks params
func (o *RepoListHooksParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repo list hooks params
func (o *RepoListHooksParams) WithHTTPClient(client *http.Client) *RepoListHooksParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repo list hooks params
func (o *RepoListHooksParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithOwner adds the owner to the repo list hooks params
func (o *RepoListHooksParams) WithOwner(owner string) *RepoListHooksParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the repo list hooks params
func (o *RepoListHooksParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the repo list hooks params
func (o *RepoListHooksParams) WithRepo(repo string) *RepoListHooksParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the repo list hooks params
func (o *RepoListHooksParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *RepoListHooksParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
