// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRepoListKeysParams creates a new RepoListKeysParams object
// with the default values initialized.
func NewRepoListKeysParams() *RepoListKeysParams {
	var ()
	return &RepoListKeysParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRepoListKeysParamsWithTimeout creates a new RepoListKeysParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRepoListKeysParamsWithTimeout(timeout time.Duration) *RepoListKeysParams {
	var ()
	return &RepoListKeysParams{

		timeout: timeout,
	}
}

// NewRepoListKeysParamsWithContext creates a new RepoListKeysParams object
// with the default values initialized, and the ability to set a context for a request
func NewRepoListKeysParamsWithContext(ctx context.Context) *RepoListKeysParams {
	var ()
	return &RepoListKeysParams{

		Context: ctx,
	}
}

// NewRepoListKeysParamsWithHTTPClient creates a new RepoListKeysParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRepoListKeysParamsWithHTTPClient(client *http.Client) *RepoListKeysParams {
	var ()
	return &RepoListKeysParams{
		HTTPClient: client,
	}
}

/*RepoListKeysParams contains all the parameters to send to the API endpoint
for the repo list keys operation typically these are written to a http.Request
*/
type RepoListKeysParams struct {

	/*Fingerprint
	  fingerprint of the key

	*/
	Fingerprint *string
	/*KeyID
	  the key_id to search for

	*/
	KeyID *int64
	/*Owner
	  owner of the repo

	*/
	Owner string
	/*Repo
	  name of the repo

	*/
	Repo string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the repo list keys params
func (o *RepoListKeysParams) WithTimeout(timeout time.Duration) *RepoListKeysParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the repo list keys params
func (o *RepoListKeysParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the repo list keys params
func (o *RepoListKeysParams) WithContext(ctx context.Context) *RepoListKeysParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the repo list keys params
func (o *RepoListKeysParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the repo list keys params
func (o *RepoListKeysParams) WithHTTPClient(client *http.Client) *RepoListKeysParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the repo list keys params
func (o *RepoListKeysParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFingerprint adds the fingerprint to the repo list keys params
func (o *RepoListKeysParams) WithFingerprint(fingerprint *string) *RepoListKeysParams {
	o.SetFingerprint(fingerprint)
	return o
}

// SetFingerprint adds the fingerprint to the repo list keys params
func (o *RepoListKeysParams) SetFingerprint(fingerprint *string) {
	o.Fingerprint = fingerprint
}

// WithKeyID adds the keyID to the repo list keys params
func (o *RepoListKeysParams) WithKeyID(keyID *int64) *RepoListKeysParams {
	o.SetKeyID(keyID)
	return o
}

// SetKeyID adds the keyId to the repo list keys params
func (o *RepoListKeysParams) SetKeyID(keyID *int64) {
	o.KeyID = keyID
}

// WithOwner adds the owner to the repo list keys params
func (o *RepoListKeysParams) WithOwner(owner string) *RepoListKeysParams {
	o.SetOwner(owner)
	return o
}

// SetOwner adds the owner to the repo list keys params
func (o *RepoListKeysParams) SetOwner(owner string) {
	o.Owner = owner
}

// WithRepo adds the repo to the repo list keys params
func (o *RepoListKeysParams) WithRepo(repo string) *RepoListKeysParams {
	o.SetRepo(repo)
	return o
}

// SetRepo adds the repo to the repo list keys params
func (o *RepoListKeysParams) SetRepo(repo string) {
	o.Repo = repo
}

// WriteToRequest writes these params to a swagger request
func (o *RepoListKeysParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fingerprint != nil {

		// query param fingerprint
		var qrFingerprint string
		if o.Fingerprint != nil {
			qrFingerprint = *o.Fingerprint
		}
		qFingerprint := qrFingerprint
		if qFingerprint != "" {
			if err := r.SetQueryParam("fingerprint", qFingerprint); err != nil {
				return err
			}
		}

	}

	if o.KeyID != nil {

		// query param key_id
		var qrKeyID int64
		if o.KeyID != nil {
			qrKeyID = *o.KeyID
		}
		qKeyID := swag.FormatInt64(qrKeyID)
		if qKeyID != "" {
			if err := r.SetQueryParam("key_id", qKeyID); err != nil {
				return err
			}
		}

	}

	// path param owner
	if err := r.SetPathParam("owner", o.Owner); err != nil {
		return err
	}

	// path param repo
	if err := r.SetPathParam("repo", o.Repo); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
