// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// RepoGetReleaseAttachmentReader is a Reader for the RepoGetReleaseAttachment structure.
type RepoGetReleaseAttachmentReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoGetReleaseAttachmentReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoGetReleaseAttachmentOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoGetReleaseAttachmentOK creates a RepoGetReleaseAttachmentOK with default headers values
func NewRepoGetReleaseAttachmentOK() *RepoGetReleaseAttachmentOK {
	return &RepoGetReleaseAttachmentOK{}
}

/*RepoGetReleaseAttachmentOK handles this case with default header values.

Attachment
*/
type RepoGetReleaseAttachmentOK struct {
	Payload *models.Attachment
}

func (o *RepoGetReleaseAttachmentOK) Error() string {
	return fmt.Sprintf("[GET /repos/{owner}/{repo}/releases/{id}/assets/{attachment_id}][%d] repoGetReleaseAttachmentOK  %+v", 200, o.Payload)
}

func (o *RepoGetReleaseAttachmentOK) GetPayload() *models.Attachment {
	return o.Payload
}

func (o *RepoGetReleaseAttachmentOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Attachment)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
