// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// RepoCreateStatusReader is a Reader for the RepoCreateStatus structure.
type RepoCreateStatusReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCreateStatusReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewRepoCreateStatusOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoCreateStatusOK creates a RepoCreateStatusOK with default headers values
func NewRepoCreateStatusOK() *RepoCreateStatusOK {
	return &RepoCreateStatusOK{}
}

/*RepoCreateStatusOK handles this case with default header values.

StatusList
*/
type RepoCreateStatusOK struct {
	Payload []*models.Status
}

func (o *RepoCreateStatusOK) Error() string {
	return fmt.Sprintf("[POST /repos/{owner}/{repo}/statuses/{sha}][%d] repoCreateStatusOK  %+v", 200, o.Payload)
}

func (o *RepoCreateStatusOK) GetPayload() []*models.Status {
	return o.Payload
}

func (o *RepoCreateStatusOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
