// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// RepoCreateReleaseReader is a Reader for the RepoCreateRelease structure.
type RepoCreateReleaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RepoCreateReleaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewRepoCreateReleaseCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRepoCreateReleaseCreated creates a RepoCreateReleaseCreated with default headers values
func NewRepoCreateReleaseCreated() *RepoCreateReleaseCreated {
	return &RepoCreateReleaseCreated{}
}

/*RepoCreateReleaseCreated handles this case with default header values.

Release
*/
type RepoCreateReleaseCreated struct {
	Payload *models.Release
}

func (o *RepoCreateReleaseCreated) Error() string {
	return fmt.Sprintf("[POST /repos/{owner}/{repo}/releases][%d] repoCreateReleaseCreated  %+v", 201, o.Payload)
}

func (o *RepoCreateReleaseCreated) GetPayload() *models.Release {
	return o.Payload
}

func (o *RepoCreateReleaseCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Release)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
