// Code generated by go-swagger; DO NOT EDIT.

package repository

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "gitea.com/sapk/explore/models"
)

// TopicSearchReader is a Reader for the TopicSearch structure.
type TopicSearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TopicSearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewTopicSearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTopicSearchOK creates a TopicSearchOK with default headers values
func NewTopicSearchOK() *TopicSearchOK {
	return &TopicSearchOK{}
}

/*TopicSearchOK handles this case with default header values.

TopicListResponse
*/
type TopicSearchOK struct {
	Payload []*models.TopicResponse
}

func (o *TopicSearchOK) Error() string {
	return fmt.Sprintf("[GET /topics/search][%d] topicSearchOK  %+v", 200, o.Payload)
}

func (o *TopicSearchOK) GetPayload() []*models.TopicResponse {
	return o.Payload
}

func (o *TopicSearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
