// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EditGitHookOption EditGitHookOption options when modifying one Git hook
// swagger:model EditGitHookOption
type EditGitHookOption struct {

	// content
	Content string `json:"content,omitempty"`
}

// Validate validates this edit git hook option
func (m *EditGitHookOption) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditGitHookOption) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditGitHookOption) UnmarshalBinary(b []byte) error {
	var res EditGitHookOption
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
