// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// ExternalWiki ExternalWiki represents setting for external wiki
// swagger:model ExternalWiki
type ExternalWiki struct {

	// URL of external wiki.
	ExternalWikiURL string `json:"external_wiki_url,omitempty"`
}

// Validate validates this external wiki
func (m *ExternalWiki) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ExternalWiki) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalWiki) UnmarshalBinary(b []byte) error {
	var res ExternalWiki
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
