// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// Organization Organization represents an organization
// swagger:model Organization
type Organization struct {

	// avatar URL
	AvatarURL string `json:"avatar_url,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// full name
	FullName string `json:"full_name,omitempty"`

	// ID
	ID int64 `json:"id,omitempty"`

	// location
	Location string `json:"location,omitempty"`

	// repo admin change team access
	RepoAdminChangeTeamAccess bool `json:"repo_admin_change_team_access,omitempty"`

	// user name
	UserName string `json:"username,omitempty"`

	// visibility
	Visibility string `json:"visibility,omitempty"`

	// website
	Website string `json:"website,omitempty"`
}

// Validate validates this organization
func (m *Organization) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Organization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Organization) UnmarshalBinary(b []byte) error {
	var res Organization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
